AbnApplicationPortal.Core/Models/ApplicationVm/DefermentViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;
using AbnApplicationPortal.Shared.Models.Intakes;
using Microsoft.AspNetCore.Mvc;

namespace AbnApplicationPortal.Core.Models.ApplicationVm
{
    public class DefermentViewModel : BaseViewModel
    {
        public DefermentViewModel() {
            ExpectedDate = DateTime.Now;
        }
        public DefermentViewModel(Deferment deferment) {
            Id = deferment.Id;
            Reason = deferment.Reason;
            //DeferPeriod = deferment.DeferPeriod;
            ApplicationId = deferment.ApplicationId;
            //ExpectedDate = deferment.ExpectedDate;
            Approval = deferment.Approval;
            Count = deferment.Count;
            Unit = deferment.Unit;
        }
        public Guid Id { get; set; }
        [Display(Name="Reason for Defering")]
        public Guid Reason { get; set; }
        [Display(Name = "Defering Period")]
        public Guid DeferPeriod { get; set; }
        [HiddenInput]
        public Guid ApplicationId { get; set; }
        [Display(Name = "Expected Reporting Date")]
        [DataType(DataType.Date)]
        public DateTime ExpectedDate { get; set; } 
        public string Approval { get; set; }
        public string PeriodString { get; set; }
        public string ReasonString { get; set; }
        [Display(Name = "Select Defer Semester or Academic Year")]
        public string Unit { get; set; }
        [Display(Name = "How Many")]
        public int Count { get; set; }
    }
}

AbnApplicationPortal.Core/Controllers/IntakeApplicationsController.cs
using AbnApplicationPortal.Core.CommProviders.Email;
using AbnApplicationPortal.Core.CommProviders.Sms;
using AbnApplicationPortal.Core.Data;
using AbnApplicationPortal.Core.Data.AppDb;
using AbnApplicationPortal.Core.Data.Unisol;
using AbnApplicationPortal.Core.Data.Unisol.Entities;
using AbnApplicationPortal.Core.Extensions;
using AbnApplicationPortal.Core.Log4Net;
using AbnApplicationPortal.Core.Models;
using AbnApplicationPortal.Core.Models.ApplicationVm;
using AbnApplicationPortal.Core.Models.AppProfileVm;
using AbnApplicationPortal.Core.Models.IntakeVm;
using AbnApplicationPortal.Core.Services;
using AbnApplicationPortal.Shared.Models;
using AbnApplicationPortal.Shared.Models.Applicants;
using AbnApplicationPortal.Shared.Models.Intakes;
using AbnApplicationPortal.Shared.Models.Logs;
using AbnApplicationPortal.Shared.Models.Settings;
using AbnApplicationPortal.Shared.Requests.Application;
using AbnApplicationPortal.Shared.Requests.Settings;
using AbnApplicationPortal.Shared.Responses;
using AbnApplicationPortal.Shared.Services;
using log4net;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Internal;
using Newtonsoft.Json;
using OfficeOpenXml;
using OfficeOpenXml.Style;
using RestSharp;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Text.RegularExpressions;
using System.Threading.Tasks;

namespace AbnApplicationPortal.Core.Controllers.Applications
{
    [Authorize]
    [Route("[controller]/[action]")]
    public class IntakeApplicationsController : Controller
    {
        private readonly AbnApplicationPortalContext _context;
        private readonly ILog _logger;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ApplicationProfileController _profileController;
        private readonly IHostingEnvironment _hostingEnvironment;
        private readonly UnisolService _unisolService;
        private readonly IEmailSender _emailSender;
        private readonly ISmsService _smsService;
        private readonly IDropDownService _dropDownService;
        private readonly IClientSettingsService _clientSettingsService;
        private const string XlsxContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";

        public IntakeApplicationsController(AbnApplicationPortalContext context, UnisolDbContext unisolDbContext,
            UserManager<ApplicationUser> userManager, IHostingEnvironment hostingEnvironment,
            IEmailSender emailSender, ISmsService smsService, IClientSettingsService clientSettingsService,
            IDropDownService dropDownService, UnisolDbContext ucontext)
        {
            _logger = AbnLogManager.Logger(typeof(IntakeApplicationsController));
            _context = context;
            _userManager = userManager;
            _profileController = new ApplicationProfileController(context, userManager);
            _hostingEnvironment = hostingEnvironment;
            _unisolService = new UnisolService(unisolDbContext, context);
            _emailSender = emailSender;
            _smsService = smsService;
            _clientSettingsService = clientSettingsService;
            _dropDownService = dropDownService;
        }

        public IActionResult Index()
        {
            if (User.IsInRole(PrimaryRole.Applicant))
            {
                return RedirectToAction(nameof(Mine));
            }
            return RedirectToAction(nameof(All));
        }

        public async Task<IActionResult> Mine()
        {
            var data = new List<ApplicationMiniViewModel>();
            try
            {
                var applications = await _context.Applications
                    .Include(a => a.ApplicationProgrammes)
                    .Where(a => a.UserId.Equals(_userManager.GetUserId(User)))
                    .OrderByDescending(a => a.DateCreated)
                    .ToListAsync();
                var uniqueIds = applications.Select(a => a.IntakeId).Distinct().ToList();
                var intakes = _context.Intakes.Where(i => uniqueIds.Contains(i.Id)).ToList();
                foreach (var application in applications)
                {
                    var intake = intakes.FirstOrDefault(i => i.Id.Equals(application.IntakeId));
                    var model = new ApplicationMiniViewModel(application)
                    {
                        IntakeCode = intake?.Code,
                        IntakeName = intake?.Name,
                        IntakeDescription = intake?.Description,
                        IntakeStatus = application.StatusStr,
                        IntakePeriod = $"{intake?.StartDateStr} - {intake?.EndDateStr}"
                    };

                    var appliedProgs = application.ApplicationProgrammes;
                    var progIds = appliedProgs.Select(p => p.ProgrammeId).Distinct().ToList();
                    var programmes = _context.Programmes.Where(p => progIds.Contains(p.Id)).ToList();
                    foreach (var programme in appliedProgs)
                    {
                        var prog = programmes.FirstOrDefault(p => p.Id.Equals(programme.ProgrammeId));
                        if (prog != null)
                        {
                            model.Programmes.Add(new ProgrammeViewModel(prog)
                            {
                                IsApproved = programme.IsApproved,
                                IsMain = programme.IsMain
                            });
                        }
                    }
                    data.Add(model);
                }
                return View(data);
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
                _logger.Error($"Error getting my applications :-{ex.Message}");
                var message = "Error occured. Try again";
                TempData.SetData(AlertLevel.Error, "My Applications", message);
                return View(data);
            }
        }

        [Authorize(Roles = "Admin,Staff,SuperAdmin")]
        public async Task<IActionResult> All(FilterApplicationsViewModel filter)
        {
            var tag = "Applications";
            try
            {
                filter.ItemsPerPage = 10;
                var applications = await GetApplicationsAsync(filter);
                return View(applications);
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
                _logger.Error($"Error getting {tag} :-{ex.Message}");
                var message = "Error occured. Try again";
                TempData.SetData(AlertLevel.Error, tag, message);
                var res = new PaginatedList<Application>(new List<Application>(), 1, 1, 1);
                return View(res);
            }
        }

        public async Task<IActionResult> ApplyIntake(Guid? intId, Guid? grtId, Guid? appId)
        {
            var tag = "Apply Intake";
            var model = new IntakeSetupViewModel();
            try
            {
                ViewData["IntId"] = intId;
                ViewData["GrtId"] = grtId;
                ViewData["AppId"] = appId;
                var profile = await _profileController.ProfileDetailsSummary(_userManager.GetUserId(User));
                if (!profile.IsComplete)
                {
                    var msg = $"Incomplete Profile:- {profile.Message}";
                    TempData.SetData(AlertLevel.Warning, tag, msg);
                    return RedirectToAction("PersonalDetails", "ApplicationProfile");
                }

                if (intId == null)
                {
                    var intake = await _context.Intakes
                    .Include(i => i.IntakeGradeTypes)
                    .FirstOrDefaultAsync(i => i.IsActive);
                    if (intake == null)
                    {
                        model.Message = "No active intake found";
                        TempData.SetData(AlertLevel.Warning, tag, model.Message);
                        return View(model);
                    }
                    model = new IntakeSetupViewModel
                    {
                        Intake = new IntakeViewModel(intake)
                    };
                }
                else
                {
                    var appIntake = await _context.Intakes.Include(i => i.IntakeGradeTypes)
                        .FirstOrDefaultAsync(i => i.Id.Equals(intId));
                    if (appIntake == null)
                    {
                        model.Message = "Provided intake not found";
                        TempData.SetData(AlertLevel.Warning, tag, model.Message);
                        return View(model);
                    }
                    model = new IntakeSetupViewModel
                    {
                        IsEditMode = true,
                        Intake = new IntakeViewModel(appIntake)
                    };
                }
                var grades = model.Intake.IntakeGradeTypes;
                var uniqueGrIds = grades.Select(gr => gr.GradeTypeId).ToList();
                var dbGradeTypes = _context.GradeCertificateTypes
                .Where(g => uniqueGrIds.Contains(g.Id))
                    .ToList();
                foreach (var item in grades)
                {
                    var type = dbGradeTypes.FirstOrDefault(g => g.Id.Equals(item.GradeTypeId));
                    var gradeTypeVm = new IntakeGradeTypeViewModel
                    {
                        GradeTypeId = item.GradeTypeId,
                        IntakeId = item.IntakeId,
                        ApplicationFee = item.ApplicationFee,
                        MaxUnits = item.MaxUnits,
                        Notes = item.Notes,

AbnApplicationPortal.Core/Views/IntakeApplications/ActiveIntakes.cshtml
@model IntakeListViewModel
@{
    Layout = "/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Active Intakes";
}





<div class="page-head">
    <h4 class="shadow-lg mt-2 mb-2 bg-light col-2 rounded p-2 text-success">@ViewData["Title"]</h4>
</div>
@if (!Model.Intakes.Any())
{
    <div class="  h-full flex justify-center items-center flex-col">
        <p class="font-bold text-white mb-8 text-lg">There are no active intakes at the moment.</p>
        <div>
            Kidly check regularly for active intakes you can apply.
        </div>
    </div>

}
else
{
    foreach (var application in Model.Intakes)
    {
        <div class="row">
            <div class="col-lg-12">
                <div class="shadow card m-b-30">
                    <div class="card-body">
                        <b style="font-size: 18px;">  @application.Intake.Name</b>&nbsp;&nbsp;  @application.Intake.StartDateStr - @application.Intake.EndDateStr

                        <p>September</p>
                        <a asp-controller="IntakeApplications" asp-action="ApplyIntake" asp-route-intId="@application.Intake.Id">View Intake <i class="mdi mdi-arrow-right"></i> </a>

                    </div>
                </div>
            </div>
        </div>
    }
}

AbnApplicationPortal.Core/Views/IntakeApplications/ApplyDeferment.cshtml
@model AbnApplicationPortal.Core.Models.ApplicationVm.DefermentViewModel

@inject IDropDownService _dropDownService;
@{
    Layout = "/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Apply for a defer";
}
    <div class="page-head">
        <h4 class="mt-2 mb-2 bg-light col-2 rounded p-2 text-success">@ViewData["Title"]</h4>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <div class="card m-b-30">
                <div class="card-body">

                    <form class="form-horizontal form-material" method="post">
                        <div class="row">
                            <input asp-for="IsEditMode" type="hidden">
                            <input asp-for="ApplicationId" />
                            <div class="form-group col-lg-4 col-sm-12">
                                <label>Select Defer Semester or Academic Year</label>
                                <select asp-for="Unit" class="form-control">
                                    <option value="">Select option</option>
                                    <option value="Semester">Semester</option>
                                    <option value="Academic Year">Academic Year</option>
                                </select>
                                <span asp-validation-for="Unit" class="text-danger"></span>
                            </div>

                            <div class="form-group col-lg-4 col-sm-12">
                                <label>How Many</label>
                                <select asp-for="Count" class="form-control">
                                    <option value="">select defer academic/semester count</option>
                                    <option value="1">1</option>
                                    <option value="2">2</option>
                                    <option value="3">3</option>
                                    <option value="4">4</option>
                                    <option value="5">5</option>
                                    <option value="6">6</option>
                                </select>
                                <span asp-validation-for="Count" class="text-danger"></span>
                            </div>

                            <div class="form-group col-lg-4 col-sm-12">
                                <label>Reason for Defering</label>
                                <select asp-for="Reason" class="form-control">
                                    <option value="">Select option</option>
                                    @foreach (var item in await _dropDownService.DeferReasons())
                                    {
                                        <option value="@item.Id" title="@item.Description">@item.Description</option>
                                    }
                                </select>
                                <span asp-validation-for="Reason" class="text-danger"></span>
                            </div>

                            <div class="form-group mt-4 offset-5 mb-0 col-lg-2 col-sm-12">
                                <button type="submit" class="btn btn-primary btn-block waves-effect waves-light">
                                    Submit
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

   

AbnApplicationPortal.Core/Views/IntakeApplications/ApplyDocuments.cshtml
@model IntakeGradeTypeViewModel
@{
    ViewData["Title"] = "Application Documents";
    Layout = "/Views/Shared/_Layout.cshtml";
    var uploaded = Model.Documents.Count(d => d.IsAdded);
    var remaining = Model.Documents.Count - uploaded;
    var suffix = remaining > 1 ? "Documents" : "Document";
}


<div class="page-head">
    <h4 class="mt-2 mb-2 bg-light text-success col-2 rounded p-2">@ViewData["Title"] </h4>
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="card m-b-30">
            <div class="card-body">
                <div class="col-lg-12">
                    @if (Model.Success)
                    {
                        <div class="container">
                            <div class="flex justify-between mb-6">
                                <div>
                                    <div class="text-2xl font-bold">
                                        Upload Documents
                                    </div>
                                    <p>
                                        Only Images & PDF documents allowed. Below 9Mbs
                                    </p>
                                </div>

                                @if (uploaded < Model.Documents.Count)
                                {
                                    <span class="p-4 bg-red-200 text-red-800 rounded-full blink_text"><i class="fa fa-times-circle"></i> You have <b>NOT</b> uploaded @remaining @suffix </span>
                                }
                            </div>

                                <form method="post" enctype="multipart/form-data" class="form-horizontal form-material" asp-action="Upload">
                                    <div class="row">
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <label for="Type"></label>
                                                <select name="DocumentId" id="DocumentId" class="select-basic form-control">
                                                    <option value="">--select document type--</option>
                                                    @foreach (var type in ViewBag.Types)
                                                    {
                                                        <option value="@type.Id">@type.Name</option>
                                                    }

                                                </select>
                                            </div>
                                        </div>
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <input type="hidden" name="ApplicationId" value="@Model.ApplicationId" />
                                                <input type="hidden" name="IsEditMode" value="" />
                                                <input name="File" type="file" accept="application/pdf,.png,.jpg" class="form-control" required="required" />
                                            </div>
                                        </div>
                                        <div class="col-md-4">
                                            <button type="submit" class="btn btn-primary btn-rounded">
                                                Upload Document
                                            </button>
                                        </div>
                                    </div>
                                </form>
                        </div>
                        <div class="col-lg-12 col-sm-12 mt-4">
                            <table id="datatable" class="table">
                                <thead>
                                    <tr>
                                        <th>
                                            Uploaded File  Name
                                        </th>
                                        <th>
                                            Document Type
                                        </th>
                                        <th>
                                            Document Category
                                        </th>

                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model.UploadDocuments)
                                    {
                                        <tr>
                                            <td>
                                                @item.Upload.Name
                                            </td>
                                            <td>
                                                @item.Document.Name
                                            </td>
                                            <td>
                                                @item.Document.Category
                                            </td>


                                        </tr>
                                    }

                                </tbody>
                            </table>
                        </div>
                        <div style="text-align:center;">
                            <a asp-action="ApplyProgrammes" asp-route-intId="@Model.IntakeId" asp-route-grtId="@Model.GradeTypeId" asp-route-appId="@Model.ApplicationId"
                               class="btn btn-danger btn-rounded"><i class="fa fa-arrow-left"></i> Back</a>

                            @if (uploaded < Model.Documents.Count)
                            {
                                <a href="javascript:void(0)" class="btn btn-primary btn-rounded">
                                    Submit Application <i class="fa fa-check"></i>
                                </a>
                            }
                            else
                            {
                                <a asp-action="ViewApplication" asp-route-id="@Model.ApplicationId" asp-route-isInit="True" class="btn btn-primary btn-rounded">
                                    Submit Your Application <i class="fa fa-check"></i>
                                </a>
                            }
                        </div>

                    }
                    else
                    {
                        <p>
                            Error getting Intake Grade Type. @Model.Message
                        </p>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

AbnApplicationPortal.Core/Views/IntakeApplications/ApplyIntake.cshtml
@model IntakeSetupViewModel
@{
    ViewData["Title"] = "Add Application";
    Layout = "/Views/Shared/_Layout.cshtml";
}

<div class="page-head">
    <h4 class="mt-2 mb-2 bg-light text-success col-2 rounded p-2">@ViewData["Title"] </h4>
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="card m-b-30">
            <div class="card-body">
                <div class="col-lg-12">
                        @if (Model.Success)
                        {
                            <div class="container">
                                <div class="bg-gray-200  rounded-lg flex flex-wrap mt-6">

                                    @if (Model.IntakeGradeTypes.Any())
                                    {
                                        var i = 0;
                                        foreach (var grade in Model.IntakeGradeTypes)
                                        {
                                            i++;
                                            <section class="mt-10 p-5 ml-2">
                                                <input asp-for="@grade.IntakeId" class="form-control" type="hidden" />
                                                <input asp-for="@grade.GradeTypeId" class="form-control" type="hidden" />
                                                <input asp-for="@grade.IsAdded" class="form-control" type="hidden" />
                                                <h5>@grade.CertType</h5>
                                                <p>@grade.CertType |   @Model.Intake.StartDateStr - @Model.Intake.EndDateStr</p>
                                                <p style="font-size: 16px;">Application Fee: <em>[  @grade.ApplicationFee]</em></p>
                                                <a asp-action="ApplyProgrammes" asp-route-intId="@grade.IntakeId" asp-route-grtId="@grade.GradeTypeId"
                                                   asp-route-appId="@Model.ApplicationId" class="btn btn-primary btn-rounded">Apply Now</a>
                                                <hr />
                                            </section>

                                        }
                                    }
                                    else
                                    {
                                        <p>
                                            No grade types Found.
                                        </p>
                                    }
                                </div>
                            </div>
                        }
                        else
                        {
                            <div>
                                <p>
                                    <i class="fa fa-info-circle fa-2x"></i> <br />	Error getting Intake. @Model.Message
                                </p>
                            </div>
                        }

                </div>
            </div>
        </div>
    </div>
</div>

AbnApplicationPortal.Core/Views/IntakeApplications/Mine.cshtml
@model List<AbnApplicationPortal.Core.Models.ApplicationVm.ApplicationMiniViewModel>


@{
    Layout = "/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "My Applications";

}
<section>


    <div class="page-head">
        <h4 class="mt-2 mb-2 bg-white text-success col-2 rounded p-2">@ViewData["Title"]</h4>
    </div>

    <div id="accordion" class="accordion">
        @if (!Model.Any())
        {
            <div class=" card p-5 h-full flex justify-center items-center flex-col">
                <p class="font-weight-bold text-black-50 mb-5 text-info">You dont have any application at the moment, click on the "add application" button below to apply.</p>
                <div>
                    <a asp-controller="IntakeApplications" asp-action="ApplyIntake" class="flex btn mx-auto text-black-50 border py-2 px-8 focus:outline-none hover:bg-yellow-600 rounded text-lg">Add Application</a>
                </div>
            </div>
        }
        else
        {
            foreach (var application in Model)
            {

                var colorClass = "";
                var bgcolor = "";

                if (application.IntakeStatus == "Pending")
                {
                    colorClass = "bg-info";
                    bgcolor = "";
                }
                if (application.IntakeStatus == "Inactive")
                {
                    colorClass = "bg-dark";
                    bgcolor = "";
                }
                if (application.IntakeStatus == "Active")
                {
                    colorClass = "bg-success";
                    bgcolor = "";
                }
                if (application.IntakeStatus == "Approved")
                {
                    colorClass = "bg-primary";
                    bgcolor = "";
                }
                if (application.IntakeStatus == "Declined")
                {
                    colorClass = "bg-danger";
                    bgcolor = "";
                }
                if (application.IntakeStatus == "Accepted")
                {
                    colorClass = "bg-success";
                    bgcolor = "";
                }
                if (application.IntakeStatus == "Defered")
                {
                    colorClass = "bg-warning";
                    bgcolor = "";
                }
                if (application.IntakeStatus == "DeferDeclined")
                {
                    colorClass = "bg-warning";
                    bgcolor = "bg-warning";
                }

                <div class="portlet" data-toggle="collapse" href="#@application.Id" >
                    <div class="portlet-heading @colorClass">
                        <h3 class="portlet-title text-white">
                            REF: @application.RefNo [@application.GradeCertTypeName]
                        </h3>
                        <div class="portlet-widgets">

                            <a  data-parent="#accordion1"  class="" aria-expanded="true"><i class="fa fa-minus"></i></a>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                    <div id="@application.Id" class="panel-collapse in collapse" style="">
                        <div class="portlet-body @bgcolor">
                            <span class="badge badge-info bg-danger">
                                @if (!application.IsFullyPaid)
                                {
                                    <span>Not Fully Paid</span>
                                }

                            </span>
                            [@application.Status]
                            <br><br> 
                            @{ var i = 0;}
                            @foreach (var item in application.Programmes)
                            {
                                i++;

                                <div class="col-lg-12">
                                    <h5>@i . @item.Code @item.Name</h5>
                                    <p>
                                        @item.Requirements
                                    </p>
                                </div>
                                <div class="row mb-3">
                                    <div class="col-md-6">
                                        <a class="btn btn-rounded btn-primary" asp-controller="IntakeApplications" asp-action="ViewApplication" asp-route-id="@application.Id"><i class="fa fa-eye"></i> View Application</a>
                                    </div>
                                    <div class="col-md-6">
                                        @if (!application.IsFullyPaid)
                                        {

                                            <a class="btn btn-rounded btn-success" asp-controller="IntakeApplications" asp-action="PayApplication" asp-route-id="@application.Id"><i class="fa fa-mobile"></i> Pay via Mpesa</a>
                                        }
                                    </div>
                                </div>
                            }
                        </div>

                    </div>

                </div>
            }<br />
            <div style="text-align:center;">
                <a asp-controller="IntakeApplications" asp-action="ActiveIntakes" class="btn btn-rounded btn-primary"><i class="fa fa-plus"></i> Apply for Intake</a>

            </div>
        }
    </div>

</section>